<?php

/**
 * @file
 * Hook implementation(s) for FLVC's policy reflector.
 */

/**
 * Implements hook_islandora_object_access().
 *
 * Allow management to objects submitters own.
 */
function flvc_policy_reflector_islandora_object_access($op, $object, $user) {
  $management_operations = array(
    ISLANDORA_MANAGE_PROPERTIES,
    ISLANDORA_METADATA_EDIT,
    ISLANDORA_ADD_DS,
  );

  $has_submitter_role = FALSE;
  foreach ($user->roles as $role) {
    if ($role == 'authUser-role') {
      $has_submitter_role = TRUE;
      break;
    }
  }

  if ($has_submitter_role && in_array($op, $management_operations)) {
    return $user->name == $object->owner;
  }

  return NULL;
}
